baseURL = 'https://artur-rios.github.io/dotnet-test-util/'
languageCode = 'en-us'
title = 'Dotnet Test Util'
theme = 'hugo-theme-re-terminal'

[module]
[[module.mounts]]
source = 'coverage-report'
target = 'static/coverage-report'

[params.logo]
logoText = 'Dotnet Test Util'

[menu]
[[menu.main]]
identifier = "author"
name = "Author"
url = "https://www.artur-rios.tech/"
[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/artur-rios/dotnet-test-util"
[[menu.main]]
identifier = "test-coverage"
name = "Test Coverage"
url = "https://artur-rios.github.io/dotnet-test-util/coverage-report"
